name: Java CI with Maven, tests and documentation generation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8 
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Ejecutando Test Unitarios
        run: | 
          sudo /etc/init.d/mysql start
          mysql -uroot -proot < src/main/resources/database.sql
          mvn --batch-mode --update-snapshots compile 
          mvn --batch-mode --update-snapshots test -PunitTest
      - name: Integration Test and Preformance Test
        run: |
          mvn --batch-mode --update-snapshots datanucleus:enhance
          mvn --batch-mode --update-snapshots datanucleus:schema-create
          mvn --batch-mode --update-snapshots test -PintegrationTest
          mvn --batch-mode --update-snapshots test -PpreformingTest 
      - name: Install doxygen
        run: sudo apt-get install -y doxygen
      - name: Test with Maven
        run: mvn test -DargLine="-Dcontiperf.active=false"
      - name: Generate documentation
        run: mvn --batch-mode --update-snapshots doxygen:report
      - name: Publish on Github Pages
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
          build_dir: target/doxygen/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

